- name: Check Jenkins Connections
  ansible.builtin.shell: "{{JENKINS_CLI_PREFIX}} who-am-i"

- name: Create a jenkins multi branch pipelines
  include_tasks: mb-job.yml
  loop:
    - {name: "sample", repoName: "sample"}
