- name: Check Jenkins Connections
  shell: "{{ JENKINS_CLI_PREFIX }} who-am-i"

- name: Create a jenkins folders
  include_tasks: folders-job.yml
  loop:
    - { name: "CI-Pipeline" , description: "All CI Pipelines" }

- name: Create a jenkins multi branch pipelines
  include_tasks: mb-job.yml
  loop:
    - { name: "cart", repoName: "cart", dirName: "CI-Pipelines/" }
